using System.Collections.Generic;
using Api2Pdf;
using BusinessLogic.Helpers;

namespace BusinessLogic.Services
{
    public class PdfService : IPdfService
    {
        private readonly Api2Pdf.Api2Pdf PdfClient;

        public PdfService(AppSettings appSettings)
        {
            PdfClient = new Api2Pdf.Api2Pdf(appSettings.ApiToPdfToken);
        }

        public string GeneratePdf(string html)
        {
            var options = new Dictionary<string, string>();
            options.Add("orientation", "portrait");
            options.Add("pageSize", "Letter");
            options.Add("footerCenter", "Generated by E-Voice");

            var request = new WkhtmlHtmlToPdfRequest
            {
                Html = html,
                Inline = true,
                Options = options,
            };

            var apiResponse = PdfClient.Wkhtml.HtmlToPdf(request);
            return apiResponse.FileUrl;
        }
    }
}